# Generated by Django 3.2.8 on 2021-10-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('note', models.TextField()),
                ('writer', models.CharField(max_length=255)),
                ('parent_no', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('insert_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now_add=True)),
                ('usage_flag', models.CharField(default='1', max_length=10)),
            ],
        ),
    ]
